name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js Setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Build Project
      - name: Build project
        run: npm run build

      # List build output
      - name: List build output
        run: ls -al build/

      # Create a Tag
      - name: Create and push tag
        id: tagging
        run: |
          TAG_NAME="v0.9.5.${{ github.run_number }}"
          
          # Delete old tag & release if exists
          gh release delete "$TAG_NAME" -y || true
          git tag -d "$TAG_NAME" || true
          git push origin :refs/tags/"$TAG_NAME" || true

          # Create new tag
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate Release Notes (Latest commit only)
      - name: Generate release notes
        id: notes
        run: |
          NOTE=$(git log -1 --pretty=format:"%s")
          echo "RELEASE_NOTES=$NOTE" >> $GITHUB_ENV

      # Create Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }}"
          body: ${{ env.RELEASE_NOTES }}
          files: |
            build/index.html
            build/index.php
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
