name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy index.html to index.php
        run: cp build/index.html build/index.php

      - name: List build directory
        run: ls -al build/

      - name: Create tag (if it doesn't exist already)
        id: create_tag
        run: |
          TAG_NAME="v0.1.${{ github.run_number }}"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -f $TAG_NAME || true
          git push origin $TAG_NAME --force

      - name: Generate release notes
        id: generate_notes
        run: |
          echo "commits=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          name: "Version ${{ steps.create_tag.outputs.tag_name }}"
          body: ${{ steps.generate_notes.outputs.commits }}
          files: |
            build/index.html
            build/index.php
            build/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
